name: Reusable workflow example

on:
  push:
    branches:
      - main


jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Out
        env:
          UPLOAD_KEY: ${{ secrets.UPLOAD_KEY }} 
        run: |
          echo UPLOAD_KEY: ${{ secrets.UPLOAD_KEY }}
          echo UPLOAD_KEY: $UPLOAD_KEY
          
