name: Reusable workflow example

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string


jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
          
      - name: Out
        env:
          UPLOAD_KEY: ${{ secrets.UPLOAD_KEY }} 
        run: |
          echo configuration-path: ${{ inputs.config-path }}
          echo UPLOAD_KEY: ${{ secrets.UPLOAD_KEY }}
          echo UPLOAD_KEY: $UPLOAD_KEY
          python test.py
