name: workflow C

on:
  push:
    branches:
      - main


jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
          
      - name: Out
        env:
          UPLOAD_KEY: ${{ secrets.UPLOAD_KEY }} 
        run: |
          echo UPLOAD_KEY: ${{ secrets.UPLOAD_KEY }}
          echo UPLOAD_KEY: $UPLOAD_KEY
          python test.py
          
